name: splitbill
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  image_picker: ^1.1.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  rxdart: ^0.28.0
  cloud_firestore:
    git:
      url: https://github.com/firebase/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore
      ref: pull/13135/head
  uuid: ^4.4.2
  currency_converter: ^0.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/default_avatar.png
  uses-material-design: true